Fixing issue #113 - Recommend PUT to return 202 for async operations
Azure/azure-resource-manager-rpc pull request #114
Opened 2021-04-27 18:31 UTC by msfcolombo

Please have a look on #113. For compatibility purposes, I've added the following section:

**IMPOTANT:** Previous versions of this document stated that PUT could return 200 OK with a non-final provisioning state and the Azure-AsyncOperation header. It is therefore recommended that whenever a client sees a 200 OK, it should check for the presence of Azure-AsyncOperation header. If the header is present, assume that the operation did not finish and start polling the URI from that header.

2021-05-12 20:47 UTC, pilor requested changes

2021-05-12 20:47 UTC, pilor commented on v1.0/Addendum.md
> +1. Respond to the initial PUT request with a 202 Accepted.
This is not correct.  The existing guidance was correct and is what ARM expects.  What is the reasoning behind making this change in the docs?

2021-05-12 20:51 UTC, msfcolombo commented on v1.0/Addendum.md
> +1. Respond to the initial PUT request with a 202 Accepted.
Hi @pilor. Please let's use #113 for discussion. I'm also adding you to internal threads.

2022-03-31 18:44 UTC, pilor commented
Closing this PR.  202 + Location is not the pattern that should be used for async PUT

2022-03-31 18:44 UTC, closed without merging