Update CMK recommended schema, including samples.
Azure/azure-resource-manager-rpc pull request #115
Opened 2021-05-29 00:23 UTC by jackrichins

2021-07-06 20:19 UTC, jackrichins commented
@pilor do you know who needs to approve this? Anyone else I should include?

2021-07-06 20:32 UTC, pilor requested changes

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +        "subProperties": {
please use with standard json schemas as they exist in openAPI v2 as that is what most RP authors will be interacting with.  Also include an example of the full schema in use (or have one of the patch examples contain the full object)

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +            "enabled": {
Given that many teams have implemented the old pattern why change from "status": "enabled/disabled" to "enabled": bool?

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +            "cmkEncryption": {
"cmk" and "kek" prefixes don't meet the Microsoft REST naming guidelines:  https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#17-naming-guidelines

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +                            "useSystemAssignedIdentity": {
This is asking for trouble when a third identity type comes into play in the future.  It should be a string enum of the form "identityType": "SystemAssigned/UserAssigned" or similar (like other places that define what identity type is used)

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +-	enabled == FALSE and properties are specified in CMK as infrastructure encryption is needed to support CMK.
can you elaborate on this?  When should enabled == false cause a validation error?

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +The following sample ARM Manifests depicts the expected state changes and service behavior.
"Manifests" means something specific for RPs.  Refer to them as requests

2021-07-06 20:32 UTC, pilor commented on v1.0/common-api-contracts.md
> +#### Partial Patch - Default Identity ####
what is the default identity that RPs are expected to use in these cases?

2021-07-06 23:44 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +            "cmkEncryption": {
I think I addressed this.

2021-07-06 23:45 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +-	enabled == FALSE and properties are specified in CMK as infrastructure encryption is needed to support CMK.
Tried to improve explaination.

2021-07-06 23:46 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +The following sample ARM Manifests depicts the expected state changes and service behavior.
Done.

2021-07-31 00:02 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +        "subProperties": {
Added full samples. I think I'm better complying with openAPI v2, but I couldn't get the tools on swagger.microsoft.com to work as this is just a spec for a fragment that an RP would add to their own schema. Any suggestions?

2021-07-31 00:03 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +                            "useSystemAssignedIdentity": {
I couldn't find a sample of string enum JSON specification - could you point me to one? I did a best effort but am sure it's not right as I only document the expected string enum values in the description.

2021-07-31 00:05 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +#### Partial Patch - Default Identity ####
I think the new schema makes this explicit. Reopen if this doesn't address your concern.

2021-08-02 17:35 UTC, pilor requested changes

2021-08-02 17:35 UTC, pilor commented on v1.0/common-api-contracts.md
> +                "type": string enum,
An example of a string enum is here:  https://github.com/Azure/azure-rest-api-specs/blob/88e7838a09868a51de3894114355c75929847a46/specification/policyinsights/resource-manager/Microsoft.PolicyInsights/stable/2021-01-01/attestations.json#L597  

You can skip the x-ms-string-enum extension since you have descriptions of the property below and the value meanings are obvious.

2021-08-02 21:04 UTC, jackrichins commented on v1.0/common-api-contracts.md
> +                "type": string enum,
Done - thanks!

2021-08-02 21:46 UTC, pilor approved these changes

2021-08-02 21:46 UTC, merged